site_name: СМ ГОЗ Opensource
site_url: https://psb-share.pages.headoffice.psbank.local/information-technology-block/smgoz/opensource

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      lang: ru
      separator: '[\s​\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - ":material-home: Домашняя": index.md
  - ":material-book: База знаний":
      - Мониторинг: home/Monitoring.md
      - Backlog: home/Backlog.md
  - ":material-tools: Эксплуатация":
      - OpenSearch:
          - Мониторы и оповещения: home/Opensearch/Monitors.md
          - Обновление кластера: home/Opensearch/Обновление-кластера.md
      - Keycloak:
          - X.509 аутентификация: home/Keycloak/X509-Authentication.md
      - Vector:
          - Логи микросервисов: home/Vector/Logging-v2.md
  - ":material-check-circle: Аудит":
      - APP EXT: home/Audit/AppExt.md
      - AUTH PROVIDER: home/Audit/AuthProvider.md
      - FRONT WEB: home/Audit/Front-Web.md
      - KAFKA APP: home/Audit/Kafka-app.md
      - LOGINOM: home/Audit/Loginom.md
      - OPENSEARCH: home/Audit/Opensearch.md
      - STORAGE: home/Audit/Storage.md
      - VECTOR ALL: home/Audit/VectorALL.md
  - ":material-account-group: Организация":
      - Группы и ТУЗ: home/ОргРаздел/Группы_и_ТУЗ_Opensource.md
      - Дежурства: home/ОргРаздел/Дежурства.md
  - ":material-lightbulb-on: Шпаргалка":
      - App VS Contour: home/Шпаргалка/AppVSContour.md
      - Bash: home/Шпаргалка/bash.md
      - Ceph: home/Шпаргалка/ceph.md
      - Consul: home/Шпаргалка/Consul.md
      - Kafka: home/Шпаргалка/kafka.md
      - OpenSearch: home/Шпаргалка/Opensearch.md
      - Репозиторий latest (RedOS): home/Шпаргалка/Включить-репозиторий-latest.md
      - IntelliJ IDEA (RedOS): home/Шпаргалка/Установка-intelliJ-IDEA-(RedOS).md
      - Postman (RedOS): home/Шпаргалка/Установка-postman-(RedOS).md
